Petalos/Models/ViewModels/FloresViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Petalos.Models.ViewModels
{
    public class FloresViewModel
    {
        public IEnumerable<DatosFloressssss> CuatroFlores { get; set; }
        public DatosFloressssss FlorUnica { get; set; }
    }

}

Petalos/Areas/Admin/Controllers/FloresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;


using Petalos.Models;
using Petalos.Areas.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using System.IO;

namespace Petalos.Controllers
{
    [Area("Admin")]
    public class FloresController : Controller
    {
        public floresContext Context { get; }
        public IWebHostEnvironment Host { get; }

        public FloresController(floresContext context, IWebHostEnvironment host)
        {
            Context = context;
            Host = host;
        }
        public IActionResult Index()
        {
            var f = Context.DatosFloressssss.OrderBy(x => x.Nombre);
            return View(f);
        }
        [HttpGet]
        public IActionResult AgregarFlor()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AgregarFlor(FloresCrud ViewModelFlores)
        {
            if (string.IsNullOrWhiteSpace(ViewModelFlores.Flor.Nombre))
            {
                ModelState.AddModelError("", "El nombre de la flor está vacío");
                return View(ViewModelFlores);
            }
            if (string.IsNullOrWhiteSpace(ViewModelFlores.Flor.NombreCientifico))
            {
                ModelState.AddModelError("", "El nombre cientifico de la flor está vacío");
                return View(ViewModelFlores);
            }
            if (string.IsNullOrWhiteSpace(ViewModelFlores.Flor.Origen))
            {
                ModelState.AddModelError("", "El origen de la flor está vacío");
                return View(ViewModelFlores);
            }
            if (string.IsNullOrWhiteSpace(ViewModelFlores.Flor.Descripcion))
            {
                ModelState.AddModelError("", "La descripción de la flor está vacía");
                return View(ViewModelFlores);
            }
            if (Context.DatosFloressssss.Any(x => x.Nombre == ViewModelFlores.Flor.Nombre))
            {
                ModelState.AddModelError("", "El nombre de la flor ya existe");
                return View(ViewModelFlores);
            }
            if (Context.DatosFloressssss.Any(x => x.NombreCientifico == ViewModelFlores.Flor.NombreCientifico))
            {
                ModelState.AddModelError("", "El nombre científico de la flor ya existe");
                return View(ViewModelFlores);
            }
            if (Context.DatosFloressssss.Any(x => x.NombreComun == ViewModelFlores.Flor.NombreComun))
            {
                ModelState.AddModelError("", "El nombre común de la flor ya existe");
                return View(ViewModelFlores);
            }
            Context.Add(ViewModelFlores.Flor);
            Context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AgregarImagenes(int id)
        {
            
            var f = Context.DatosFloressssss.Include(x => x.ImagenesFlores).FirstOrDefault(x => x.Idflor == id);
            if (f == null)
            {
                return RedirectToAction("Index");
            }
            FloresCrud vm = new();
            vm.ImagenId = Context.Imagenesflores.FirstOrDefault(x => x.IdFlor == f.Idflor);
            vm.Flor = f;
          
            vm.Flores = Context.DatosFloressssss.OrderBy(x => x.Nombre);
          
            return View(vm);

             
          
        }
        [HttpPost]
        public IActionResult AgregarImagenes(FloresCrud ViewModelFlores,IFormFile foto)
        {
            if (foto==null)
            {    
                ViewModelFlores.Flores = Context.DatosFloressssss.OrderBy(x => x.Nombre);
                ModelState.AddModelError("", "No hay ninguna fotografía");
                return View(ViewModelFlores);
            }
            if (foto != null)
            {
                if (foto.ContentType != "image/jpeg")
                {
                    ModelState.AddModelError("", "Solo se permite la carga de archivos .jpg");
                    return View(ViewModelFlores);

                }
                if (foto.Length > 1024 * 1024 * 5)
                {
                    ModelState.AddModelError("", "No se permite la carga de archivos mayores a 5MB");
                    return View(ViewModelFlores);
                }
            }
            ViewModelFlores.ImagenId.NombreImagen = foto.FileName;
            Context.Add(ViewModelFlores.ImagenId);
           
            Context.SaveChanges();
            if (foto != null)
            {
                String var = "Hola a todo mundo";
                int tam_var = var.Length;
                String Var_Sub = var.Substring((tam_var - 2), 2);
                var path = Host.WebRootPath + "/images/" + ViewModelFlores.ImagenId.NombreImagen /*+ ".jpg"*/;
                FileStream fs = new FileStream(path, FileMode.Create);
                foto.CopyTo(fs);
                fs.Close();
            }
            return RedirectToAction("AgregarImagenes");
          
        }
        [HttpGet]
        public IActionResult EditarFlor(int id)
        {
            var f = Context.DatosFloressssss.FirstOrDefault(x => x.Idflor == id);
            if (f == null)
            {
                return RedirectToAction("Index");
            }

            FloresCrud vm = new FloresCrud
            {
                Flor = f
            };

            return View(vm);

        }
        [HttpPost]
        public IActionResult EditarFlor(FloresCrud ViewModelFlores)
        {

            var f = Context.DatosFloressssss.FirstOrDefault(x => x.Idflor == ViewModelFlores.Flor.Idflor);
            if (f == null)
            {
                return RedirectToAction("Index");
            }
            if (string.IsNullOrWhiteSpace(ViewModelFlores.Flor.Nombre))
            {
                ModelState.AddModelError("", "El nombre de la flor está vacío");
                return View(ViewModelFlores);
            }
            if (string.IsNullOrWhiteSpace(ViewModelFlores.Flor.NombreCientifico))
            {
                ModelState.AddModelError("", "El nombre científico de la flor está vacío");
                return View(ViewModelFlores);
            }
            if (string.IsNullOrWhiteSpace(ViewModelFlores.Flor.Origen))
            {
                ModelState.AddModelError("", "El origen de la flor está vacío");
                return View(ViewModelFlores);
            }
            if (string.IsNullOrWhiteSpace(ViewModelFlores.Flor.Descripcion))
            {
                ModelState.AddModelError("", "La descripción de la flor está vacía");
                return View(ViewModelFlores);
            }
            if (Context.DatosFloressssss.Any(x => x.Nombre == ViewModelFlores.Flor.Nombre && x.Idflor != ViewModelFlores.Flor.Idflor))
            {
                ModelState.AddModelError("", "El nombre de la flor ya existe");
                return View(ViewModelFlores);
            }
            if (Context.DatosFloressssss.Any(x => x.NombreCientifico == ViewModelFlores.Flor.NombreCientifico && x.Idflor != ViewModelFlores.Flor.Idflor))
            {
                ModelState.AddModelError("", "El nombre científico de la flor ya existe");
                return View(ViewModelFlores);
            }
            if (Context.DatosFloressssss.Any(x => x.NombreComun == ViewModelFlores.Flor.NombreComun && x.Idflor != ViewModelFlores.Flor.Idflor))
            {
                ModelState.AddModelError("", "El nombre común de la flor ya existe");
                return View(ViewModelFlores);
            }
            f.NombreCientifico = ViewModelFlores.Flor.NombreCientifico;
            f.NombreComun = ViewModelFlores.Flor.NombreComun;
            f.Origen = ViewModelFlores.Flor.Origen;
            f.Descripcion = ViewModelFlores.Flor.Descripcion;
            f.Nombre = ViewModelFlores.Flor.Nombre;
            Context.Update(f);
            Context.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult EliminarFlor(int id)
        {
            var f = Context.DatosFloressssss.FirstOrDefault(x => x.Idflor == id);
            if (f == null)
            {
                return RedirectToAction("Index");
            }
            return View(f);
        }
        [HttpGet]
        public IActionResult EliminarImagen(int id)
        {
            var img = Context.Imagenesflores.FirstOrDefault(x => x.IdImagen == id);
            if (img == null)
            {
                return RedirectToAction("Index");
            }
            return View(img);
        }
        [HttpPost]
        public IActionResult EliminarImagen(Imagenesflores imagenF)
        {
            var img = Context.Imagenesflores.FirstOrDefault(x => x.IdImagen == imagenF.IdImagen);

            if (img == null)
            {
                ModelState.AddModelError("", $"La fotografía {imagenF.NombreImagen} ha sido eliminada, o no existe");
                return View(imagenF);
            }
            Context.Remove(img);
            Context.SaveChanges();
            string path = Host.WebRootPath + "/images/" + img.NombreImagen;
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult EliminarFlor(DatosFloressssss flor)
        {
            var f = Context.DatosFloressssss.FirstOrDefault(x => x.Idflor == flor.Idflor);

            if (f == null)
            {
                ModelState.AddModelError("", "La flor no existe o ya ha sido eliminada");
                return View(flor);
            }
            Context.Remove(f);
            Context.SaveChanges();

            return RedirectToAction("Index");
        }

    }


}

Petalos/Areas/Admin/Views/Flores/AgregarFlor.cshtml
@model Petalos.Areas.Models.ViewModels.FloresCrud
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{
    Layout = "_Layout";
}
<h2 class="titulo">Agregar flor </h2>
<form method="post" asp-area="Admin" asp-action="AgregarFlor" asp-controller="Flores">
    <label>Nombre:</label><input asp-for="Flor.Nombre" type="text" /><br />
    <label>Nombre Científico:</label><input asp-for="Flor.NombreCientifico" type="text" /><br />
    <label>Nombre Común:</label><input asp-for="Flor.NombreComun" type="text" /><br />
    <label>Origen:</label><input asp-for="Flor.Origen" type="text" /><br />
    <label>Descripción:</label><textarea asp-for="Flor.Descripcion" rows="5"></textarea><br />
    <p style="color:blueviolet;font-size:15px">
     
       @Html.ValidationSummary()
    </p>
    <input style="float:left" type="submit" value="Agregar" />
    <a href="~/admin/" style=" line-height: 18px; width: 100px; height: 18px; display: block; text-align: center; text-decoration: none; background-color: #025975; color: white; padding: 5px; border: 1px solid black; float: left; margin-top:15px ; margin-left: 60px ">
    </a>
</form>

Petalos/Areas/Admin/Views/Flores/AgregarImagenes.cshtml
@model Petalos.Areas.Models.ViewModels.FloresCrud
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{ Layout = "_Layout"; }

<h2 class="titulo">Agregar una imagen para la flor</h2>

<form method="post" asp-area="Admin" asp-controller="Flores" asp-action="AgregarImagenes" enctype="multipart/form-data">

   
    <label>Flor:</label><input readonly="readonly" asp-for="Flor.Nombre"/><br />
    <label>Archivo:</label><input type="file" id="fileImage" name="foto" accept="image/jpeg" /><br />
    <p style="color:red;font-size:15px">
        @Html.ValidationSummary()
    </p>
    <div>
        <input style="float:left" type="submit" value="Agregar" />

        <input hidden  asp-for="ImagenId.NombreImagen" type="text" value="NombreQueSeraCambiado" />
        <select hidden   required asp-for="ImagenId.IdFlor"   asp-items="@(new SelectList(Model.Flores, "Idflor", "Nombre"))">
         <option selected>@Model.Flor.Idflor</option>
        </select>
        <a href="~/admin/" style="float: left; line-height: 18px; width: 100px; height: 18px; display: block; text-align: center; text-decoration: none; background-color: #025975; color: white; padding: 5px; border: 1px solid black; margin-top: 15px; margin-left: 20px ">
        </a>
    </div>

</form>
<br />
<br />

<div class="listaImagenes">
    <ul>
        @foreach ( var fotoFlor in Model.Flor.ImagenesFlores)
        {
<li>
    <img src='~/images/@(fotoFlor.NombreImagen)' />
    <a style="font-size:20px; text-decoration:none" href='~/Admin/Flores/EliminarImagen/@(fotoFlor.IdImagen)'>Eliminar🗑️</a>
</li>}
    </ul>
</div>

<br class="clear" />

<script>function mostrarImagen(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                document.querySelector('#imagePreview').src = e.target.result;
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    document.querySelector("#fileImage").addEventListener("change", event => {
        mostrarImagen(event.target)
    });</script>

Petalos/Areas/Admin/Views/Flores/EditarFlor.cshtml
@model Petalos.Areas.Models.ViewModels.FloresCrud
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{
    Layout = "_Layout";
}
<h2 class="titulo">Editar flor</h2>
<form method="post" asp-area="Admin" asp-action="EditarFlor" asp-controller="Flores">
    <input hidden asp-for="Flor.Idflor" />
    <label>Nombre:</label><input asp-for="Flor.Nombre" type="text" /><br />
    <label>Nombre Cientifico:</label><input asp-for="Flor.NombreCientifico" type="text" /><br />
    <label>Nombre Común:</label><input asp-for="Flor.NombreComun" type="text" /><br />
    <label>Origen:</label><input asp-for="Flor.Origen" type="text" /><br />
    <label>Descripción:</label><textarea asp-for="Flor.Descripcion" rows="5"></textarea><br />
    <p style="color:red;font-size:15px">
        @Html.ValidationSummary()
    </p>
    <input style="font-size:25px;padding:5px;font-weight:bold;height:50px;float:left" 
           type="submit" value="&#128190" />

    <a href="~/admin/" style=" line-height: 18px; width: 100px; height:
     18px; display: block; text-align: center; text-decoration: none;
           background-color: #025975; color: whitesmoke; padding: 5px; border:
               1px black; float: left; margin-top: 16px; margin-left: 20px;height:38px;display:block;line-height:38px ">
    </a>
</form>

Petalos/Areas/Admin/Views/Flores/EliminarFlor.cshtml
@model Petalos.Models.DatosFloressssss
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{
    ViewData["Title"] = "EliminarFlor";
    Layout= "_Layout";
}

<div style="width:100%" @*id="crudM" style=" display: block; width: 50%; margin: auto; left: 20%; position: relative;"*@>
    
    <p  style="color:#025975;font-size:20px;width: 100%; text-align: center; font-size: larger; display: block;">¿Seguro de eliminar la flor <b>@(Model.Nombre)</b>?</p>
   <br />
   <form method="post" asp-area="Admin" asp-controller="Flores" asp-action="EliminarFlor">
       <input asp-for="Nombre" value="@(Model.Nombre)" hidden />
       <input asp-for="Idflor" value="@(Model.Idflor)" hidden />
       <p style="color:red;text-align:center; font-size:15px">
           @Html.ValidationSummary()
       </p>
       <div style="margin-left:350px">
           <input style="float:left;width:100px;margin:auto" type="submit" value="Eliminar">
           <a href="~/admin/" style=" line-height: 18px; width: 100px; height: 18px; display: block; text-align: center; text-decoration: none; background-color: #025975; color: whitesmoke; padding: 5px; border: 1px black; float: left; margin-left: 20px ">
           </a>
       </div>


   </form>

</div>


<br class="clear" />

Petalos/Areas/Admin/Views/Flores/EliminarImagen.cshtml
@model Petalos.Models.Imagenesflores
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment env
@{ Layout = "_Layout"; }

<div style="width:100%" >

    <p style="color:#025975;font-size:20px;width: 100%; text-align: center; font-size: larger; display: block;">¿Seguro que quiere eliminar la imagen <b>@(Model.NombreImagen)</b>?</p>
    @if (System.IO.File.Exists($"{env.WebRootPath}/images/{Model.NombreImagen}"))
    {
    <img  style="color:whitesmoke;width:300px;height:300px; margin-left:320px" id="imagePreview" src="~/images/@(Model.NombreImagen)" alt="Vista previa de la imagen"> }
    else
    {
    <img style="color:whitesmoke;width:300px;height:300px; margin-left:320px" id="imagePreview" src="~/img/NotFound.png" alt="Vista previa de la imagen">}
    <br />
    <form method="post" asp-area="Admin" asp-controller="Flores" asp-action="EliminarImagen">
        <input asp-for="NombreImagen" value="@(Model.NombreImagen)" hidden />
        <input asp-for="IdImagen" value="@(Model.IdImagen)" hidden />
        <p style="color:red;text-align:center; font-size:15px">
            @Html.ValidationSummary()
        </p>
        <div style="float:right">
            <input style="float:left;width:100px;margin:auto" type="submit" value="Eliminar">
            <a href="~/admin/" style=" line-height: 18px; width: 100px; height: 18px; display: block; text-align: center; text-decoration: none; background-color: #025975; color: white; padding: 5px; border: 1px solid black; float: left; margin-left: 20px ">
                
            </a>
        </div>


    </form>

</div>

Petalos/Areas/Admin/Views/Flores/Index.cshtml
@model IEnumerable<Petalos.Models.DatosFloresssss>
@{
    Layout = "_Layout";
}

<h2 class="titulo">Lista de las flores</h2>

<p>
    <a class="button" href="~/Admin/Flores/AgregarFlor">Agregar Flor</a>
    <a class="button" href="/">Salir</a>
</p>

<div class="entrada">

    <table id="tablaFlores" style="width: 100%;">
        <tr style="background: #cc76ff;">
            <th>Flor</th>
            <th style="width: 48%">Acción</th>
        </tr>

        @foreach (var f in Model)
        {
            <tr>
                <td>@f.Nombre</td>
                <td>
                    <a href="~/Admin/Flores/AgregarImagenes/@(f.Idflor)">Agregar Imágenes</a>
                    <a href='~/Admin/Flores/EditarFlor/@(f.Idflor)'>Editar</a>
                    <a href='~/Admin/Flores/EliminarFlor/@(f.Idflor)'>Eliminar</a>
                </td>
            </tr>
        }




    </table>
    @*<a  style=" line-height: 18px; width: 100px; height: 18px; display: block; text-align: center; text-decoration: none; background-color: #3c83bc; color: white; padding: 5px; border: 1px solid black; float: right; margin-top:40px; margin-left:20px " href="~/Admin/Flores/AgregarImagenes">Agregar Imagenes</a>*@

    <div id="popConfirmacion" class="popup" runat="server">
        <div>
            <h1>Por favor, confirme:</h1>
            <p id="mensajeConfirmacion" runat="server">¿Está seguro de eliminar los datos e imágenes de la flor seleccionada?</p>
            <input type="button" value="Si" />
            <input type="button" value="No" />
        </div>
    </div>

</div>